credentials:
  usernames:
    Pinkpanther:
      email:
      name: Pinkpanther
      password: $2b$12$OwT1PCt0FSH5QTlOz1IdJ.h11fAbMKxTkx5SbMdaI312NwENIb0Ku
    guest:
      name: Gast
      password: $2b$12$tK8SbVmvMUakwq1ADl2sgOGoeQY6AcRsHSJhZc672.517Cg23kLZK # To be replaced with hashed password
    TFT:
      name: Test_1
      password: $2b$12$evBYd2O94ASdw6DCShtHGu6T/MN/KodunYQIFNgCYi4bTn92tPWPC
    Spiel:
      name: Test_2
      password: $2b$12$zQ39usMbC3PFuvdYUulMSOyEk71wWF8W1hpokpaaLsHWP.b7i/8/m
    Sport:
      name: Test_3
      password: $2b$12$hB0MJw4ZRR1YhALIJlbvgOzAfnVmjlXbQZu/T2oDBE/Zv1a0yS/.q
    Reiten:
      name: Test_4
      password: $2b$12$ntZ1HbaLY2WTN11FYA815ujP7IfqsNB7rOjKavCyqhq5xeqiQDXbm
    Surfen:
      name: Test_5
      password: $2b$12$tiiSC7CqlIhl06r0.D.n2.ZHTgIlOQhzP3eBm5Mw4CadHxP6qZ.C6
    Green:
      name: Test_5
      password: $2b$12$Fcyn3o55BcrEb13WqidtYefzJdtmzIMgRN6ReidLXZ6hPkP1aLNSi
      
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: JgDyEoKUNItM5prxo194jDeLYzVzmYE6 # Must be string, use https://randomkeygen.com/
  name: streamlitcookie
