credentials:
  usernames:
    Tamara Aneni:
      email: 
      name: Tamara Aneni
      password: $2b$12$uVZI/XV9ty.3klP4F9oGHOIwXFCktChAof0Ij.dJK3PtgA1e5akXq # To be replaced with hashed password
    guest:
      name: Gast
      password:  $2b$12$uVZI/XV9ty.3klP4F9oGHOIwXFCktChAof0Ij.dJK3PtgA1e5akXq # To be replaced with hashed password
cookie:
  expiry_days: 3000  # number of days until password is asked again
  key: 645f5fe0b89b1e22999cced3 # Must be string, use https://randomkeygen.com/
  name: streamlitcookie

 
